### PR TITLE
updated plotting and examples

### PR DESCRIPTION
**Pull request by maudeinhorn**
- updated add_dos and add_cum_kappa functions in tp.plot.frequency
- added dashed xaxis line in formatting function in tp.plot.phonons
- corrected axis labels settings
- updated examples folder and docs/src/figures
- rebuilt docs

### CODE REVIEW

**Comment by kbspooner** [comment]
The concepts here are good, but theres a couple implementation problems:
 * In `frequency.py`, setting `line=False` doesn't do what you'd expect in `add_dos` or `add_cum_kappa`, the colour handling and plotting logic will need updating.
 * In `phonons.py` , should the 0-line and high-symmetry-point lines share the same kwargs? Somone may want one but not the other (or maybe not, this could be the simplest way).
And a couple of minors:
 * The new default for `line` in `add_dos` should be reflected in the docstring.
 * The correction for `doping` should also be in `short_labels`.

**Comment by kbspooner** [comment]
wrt the line in `phonons.py`, that would also avoid a potential conflict if one were to specify the linestyle for the vertical lines.

**Comment by maudeinhorn** [comment]
Apologies Dr. Spooner, think all of those issues should now be fixed

**Comment by kbspooner** [comment]
I am afraid, Fräulein Einhorn, that while you have indeed corrected the minor errors and `add_dos`, that you have neglected to perform the same correction to `add_cum_kappa`. Furthermore, there is a slight hitch in the current implementation, whereby if `line=False` and `fill=True`, no label will be attached in `add_dos`. Please correct these blunders posthaste.

**Pull request merged**
